Repository CS2103-AY1819S2-W10-3/main, pull requests merged in 2019-02, with the labels that each got.

#2 Stroage: Add backupAddressBook(ReadOnlyAddressBook)
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: enhancement

#9 Remove Getting started points from DG
  docs/DeveloperGuide.adoc
Labels: documentation, v1.1

#12 refactored model component - uniquepersonlist
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/equipment/Equipment.java
  src/main/java/seedu/address/model/equipment/UniqueEquipmentList.java
  src/main/java/seedu/address/model/equipment/exceptions/DuplicateEquipmentException.java
  src/main/java/seedu/address/model/equipment/exceptions/EquipmentNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/equipment/EquipmentTest.java
  src/test/java/seedu/address/model/equipment/UniqueEquipmentListTest.java
Labels: v1.1
