Repository CS2103-AY1819S2-W10-3/main, pull requests merged in 2019-03, with the labels that each got.

#14 refactored versionedAddressBook to versionedEquipmentManager
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedEquipmentManager.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
  src/test/java/seedu/address/model/VersionedEquipmentManagerTest.java
Labels: type.Task, v1.1

#15 Rename addressbook to equipmentManager
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/storage/JsonEquipmentManagerStorage.java
  src/test/data/JsonEquipmentManagerStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonEquipmentManagerStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonEquipmentManagerStorageTest/notJsonFormatAddressBook.json
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonEquipmentManagerStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
Labels: type.Task, v1.1

#18 Refactor PersonCard to EquipmentCard
  src/main/java/seedu/address/ui/EquipmentCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/guitests/guihandles/PersonListPanelHandle.java
  src/test/java/seedu/address/ui/EquipmentCardTest.java
Labels: type.Task, v1.1

#20 Changes in storage
  LICENSE
  README.adoc
  _config.yml
  appveyor.yml
  build.gradle
  docs/DeveloperGuide.adoc
  gradle.properties
  src/main/java/seedu/address/storage/EquipmentManagerStorage.java
  src/main/java/seedu/address/storage/StorageManager.java
Labels: type.Task, v1.1

#24 Edit equipment details
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/equipment/Name.java
  src/main/java/seedu/address/model/equipment/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedEquipment.java
  src/main/java/seedu/address/storage/JsonSerializableEquipmentManager.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/EquipmentCard.java
  src/main/java/seedu/address/ui/EquipmentListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/EquipmentListPanel.fxml
  src/test/java/guitests/guihandles/EquipmentCardHandle.java
  src/test/java/guitests/guihandles/EquipmentListPanelHandle.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/equipment/NameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEquipmentTest.java
  src/test/java/seedu/address/testutil/EquipmentUtil.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/EquipmentListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: type.Enhancement, type.Story, type.Task, v1.2

#29 Update component diagram
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation, type.Enhancement, v1.2

#36 Update class diagrams
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation, status.Ongoing, v1.2

#37 documentation for select command and others
  docs/UserGuide.adoc
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/ui/EquipmentCard.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: documentation, v1.2

#42 Add a display map web page.
  build.gradle
  docs/displaymap/index.html
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DisplayCommand.java
  src/main/java/seedu/address/logic/parser/DisplayCommandParser.java
  src/main/java/seedu/address/model/equipment/Name.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium, type.Story, v1.2

#41 Enhance equipment details
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/EquipmentManager.java
  src/main/java/seedu/address/model/equipment/Equipment.java
  src/main/java/seedu/address/model/equipment/Name.java
  src/main/java/seedu/address/model/equipment/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/equipment/SerialNumber.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEquipment.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/EquipmentCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonEquipmentManagerStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonEquipmentManagerStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableEquipmentManagerTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableEquipmentManagerTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableEquipmentManagerTest/typicalPersonsAddressBook.json
  src/test/java/guitests/guihandles/EquipmentCardHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/equipment/EquipmentTest.java
  src/test/java/seedu/address/model/equipment/NameTest.java
  src/test/java/seedu/address/model/equipment/SerialNumberTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEquipmentTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EquipmentBuilder.java
  src/test/java/seedu/address/testutil/EquipmentUtil.java
  src/test/java/seedu/address/testutil/TypicalEquipments.java
  src/test/java/seedu/address/ui/EquipmentListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.High, type.Enhancement, type.Story, v1.2

#45 Modify doc publish
  build.gradle
  docs/staticpages/DisplayGmap.html
Labels: priority.High, type.Enhancement, type.bug, v1.2

#47 Update test
  src/main/java/seedu/address/model/equipment/WorkList.java
  src/test/java/systemtests/EquipmentManagerSystemTest.java
Labels: priority.High, type.bug, v1.2

#48 Remove header from documentation page
  docs/templates/_header.html.slim
  docs/templates/document.html.slim
Labels: priority.High, type.Task, v1.2

#49 Add proper header
  docs/templates/_header.html.slim
  docs/templates/document.html.slim
Labels: priority.High, type.Task, v1.2

#50 Implement display function
  src/main/java/seedu/address/logic/parser/DisplayCommandParser.java
  src/main/java/seedu/address/logic/parser/EquipmentManagerParser.java
  src/main/java/seedu/address/model/equipment/Equipment.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/DisplayCommandTest.java
  src/test/java/systemtests/DisplayCommandSystemTest.java
Labels: priority.Low, type.Story, v1.2

#51 Added a class, WorkListId
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/model/equipment/WorkList.java
  src/main/java/seedu/address/model/equipment/WorkListId.java
  src/test/java/seedu/address/model/equipment/WorkListTest.java
Labels: priority.Medium, type.Story, v1.2

#52 Add FilterCommand
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/EquipmentManagerParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagsContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParser.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/systemtests/DisplayCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.High, type.Story, v1.2

#58 Update command word
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: type.Enhancement, type.Task, v1.2

#59 Enhance equipment components and testing
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/equipment/Equipment.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEquipmentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EquipmentManagerParserTest.java
  src/test/java/seedu/address/model/equipment/EquipmentTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EquipmentUtil.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.High, type.Task, v1.2

#60 FilterCommand to filter by multiple fields & refactor person to equipment
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/equipment/EquipmentContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/equipment/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/TagsContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParser.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: documentation, priority.High, type.Story, type.Task, v1.2

#62 Update display docs
  docs/DeveloperGuide.adoc
  docs/diagrams/DisplaySequenceDiagram.pptx
  docs/images/DisplaySequenceDiagram.png
Labels: priority.High, type.Task, v1.2

#63 Change datas in equipments to client names
  docs/images/UI.png
  docs/images/Ui.png
  src/test/data/JsonSerializableEquipmentManagerTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/EquipmentManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/VersionedEquipmentManagerTest.java
  src/test/java/seedu/address/model/equipment/EquipmentTest.java
  src/test/java/seedu/address/model/equipment/UniqueEquipmentListTest.java
  src/test/java/seedu/address/model/equipment/WorkListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEquipmentTest.java
  src/test/java/seedu/address/storage/JsonEquipmentManagerStorageTest.java
  src/test/java/seedu/address/testutil/TypicalEquipments.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: documentation, priority.High, type.Task, v1.2

#64 Update User Guide and Developer Guide for display command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.Low, type.Task, v1.2

#65 Added list-w command
  src/main/java/seedu/address/logic/commands/ListEquipmentCommand.java
  src/main/java/seedu/address/logic/commands/ListWorkListCommand.java
  src/main/java/seedu/address/logic/parser/EquipmentManagerParser.java
  src/main/java/seedu/address/model/EquipmentManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/equipment/UniqueWorkListList.java
  src/main/java/seedu/address/model/equipment/WorkList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListEquipmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ListWorkListCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/EquipmentManagerParserTest.java
  src/test/java/seedu/address/model/EquipmentManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/equipment/UniqueWorkListListTest.java
  src/test/java/seedu/address/model/equipment/WorkListTest.java
  src/test/java/seedu/address/testutil/TypicalWorkLists.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/EquipmentManagerSystemTest.java
Labels: priority.High, type.Story, v1.2

#68 Refactor WorkList and WorkListId
  src/main/java/seedu/address/model/EquipmentManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UniqueWorkListList.java
  src/main/java/seedu/address/model/WorkList.java
  src/main/java/seedu/address/model/WorkListId.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/UniqueWorkListListTest.java
  src/test/java/seedu/address/model/WorkListTest.java
  src/test/java/seedu/address/testutil/TypicalWorkLists.java
Labels: priority.Low, type.Enhancement, v1.3

#73 UG and DG Update for v1.3
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: documentation, status.Ongoing, type.Story, type.Task, v1.3

#75 Modify SortCommand to support specific fields
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/equipment/commons/core/Messages.java
  src/main/java/seedu/equipment/logic/commands/SortCommand.java
  src/main/java/seedu/equipment/logic/parser/EquipmentManagerParser.java
  src/main/java/seedu/equipment/model/EquipmentManager.java
  src/main/java/seedu/equipment/model/Model.java
  src/main/java/seedu/equipment/model/ModelManager.java
  src/main/java/seedu/equipment/model/equipment/Address.java
  src/main/java/seedu/equipment/model/equipment/Email.java
  src/main/java/seedu/equipment/model/equipment/Name.java
  src/main/java/seedu/equipment/model/equipment/Phone.java
  src/main/java/seedu/equipment/model/equipment/UniqueEquipmentList.java
  src/test/java/seedu/equipment/logic/commands/AddCommandTest.java
  src/test/java/seedu/equipment/logic/commands/CommandTestUtil.java
  src/test/java/seedu/equipment/logic/commands/SortCommandTest.java
Labels: documentation, priority.Medium, status.Ongoing, type.Task, v1.3

#79 add-w command
  src/main/java/seedu/equipment/logic/commands/AddEquipmentCommand.java
  src/main/java/seedu/equipment/logic/commands/AddWorkListCommand.java
  src/main/java/seedu/equipment/logic/parser/AddEquipmentCommandParser.java
  src/main/java/seedu/equipment/logic/parser/AddWorkListCommandParser.java
  src/main/java/seedu/equipment/logic/parser/CliSyntax.java
  src/main/java/seedu/equipment/logic/parser/EquipmentManagerParser.java
  src/main/java/seedu/equipment/logic/parser/ParserUtil.java
  src/main/java/seedu/equipment/model/Model.java
  src/main/java/seedu/equipment/model/ModelManager.java
  src/test/java/seedu/equipment/logic/LogicManagerTest.java
  src/test/java/seedu/equipment/logic/commands/AddEquipmentCommandIntegrationTest.java
  src/test/java/seedu/equipment/logic/commands/AddEquipmentCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddWorkListCommandTest.java
  src/test/java/seedu/equipment/logic/commands/CommandTestUtil.java
  src/test/java/seedu/equipment/logic/parser/AddEquipmentCommandParserTest.java
  src/test/java/seedu/equipment/logic/parser/AddWorkListCommandParserTest.java
  src/test/java/seedu/equipment/logic/parser/EquipmentManagerParserTest.java
  src/test/java/seedu/equipment/logic/parser/ParserUtilTest.java
  src/test/java/seedu/equipment/model/ModelManagerTest.java
  src/test/java/seedu/equipment/testutil/EquipmentUtil.java
  src/test/java/seedu/equipment/testutil/TypicalWorkLists.java
  src/test/java/seedu/equipment/testutil/WorkListBuilder.java
  src/test/java/systemtests/AddEquipmentCommandSystemTest.java
Labels: priority.Medium, type.Story, v1.3

#80 Equipment enhancement
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/templates/_header.html.slim
  src/main/java/seedu/equipment/logic/commands/AddCommand.java
  src/main/java/seedu/equipment/logic/commands/EditCommand.java
  src/main/java/seedu/equipment/logic/commands/SortCommand.java
  src/main/java/seedu/equipment/logic/parser/AddCommandParser.java
  src/main/java/seedu/equipment/logic/parser/AddWorkListCommandParser.java
  src/main/java/seedu/equipment/logic/parser/CliSyntax.java
  src/main/java/seedu/equipment/logic/parser/EditCommandParser.java
  src/main/java/seedu/equipment/logic/parser/EquipmentManagerParser.java
  src/main/java/seedu/equipment/logic/parser/ParserUtil.java
  src/main/java/seedu/equipment/model/EquipmentManager.java
  src/main/java/seedu/equipment/model/equipment/Date.java
  src/main/java/seedu/equipment/model/equipment/Email.java
  src/main/java/seedu/equipment/model/equipment/Equipment.java
  src/main/java/seedu/equipment/model/equipment/EquipmentContainsKeywordsPredicate.java
  src/main/java/seedu/equipment/model/util/SampleDataUtil.java
  src/main/java/seedu/equipment/storage/JsonAdaptedEquipment.java
  src/main/java/seedu/equipment/ui/EquipmentCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonEquipmentManagerStorageTest/invalidAndValidEquipmentEM.json
  src/test/data/JsonEquipmentManagerStorageTest/invalidEquipmentEM.json
  src/test/data/JsonSerializableEquipmentManagerTest/duplicateEquipmentEM.json
  src/test/data/JsonSerializableEquipmentManagerTest/typicalEquipmentEM.json
  src/test/java/guitests/guihandles/EquipmentCardHandle.java
  src/test/java/seedu/equipment/logic/LogicManagerTest.java
  src/test/java/seedu/equipment/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/equipment/logic/commands/AddCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddWorkListCommandTest.java
  src/test/java/seedu/equipment/logic/commands/CommandTestUtil.java
  src/test/java/seedu/equipment/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/equipment/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/equipment/logic/parser/EquipmentManagerParserTest.java
  src/test/java/seedu/equipment/logic/parser/ParserUtilTest.java
  src/test/java/seedu/equipment/model/equipment/DateTest.java
  src/test/java/seedu/equipment/model/equipment/EmailTest.java
  src/test/java/seedu/equipment/model/equipment/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/equipment/storage/JsonAdaptedEquipmentTest.java
  src/test/java/seedu/equipment/testutil/EditEquipmentDescriptorBuilder.java
  src/test/java/seedu/equipment/testutil/EquipmentBuilder.java
  src/test/java/seedu/equipment/testutil/EquipmentUtil.java
  src/test/java/seedu/equipment/testutil/TypicalEquipments.java
  src/test/java/seedu/equipment/ui/EquipmentListPanelTest.java
  src/test/java/seedu/equipment/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.High, type.Enhancement, type.Story, type.Task, v1.3

#83 add addworklistcommand to equipment parser
  src/main/java/seedu/equipment/logic/parser/EquipmentManagerParser.java
Labels: severity.Low, type.Task, type.bug, v1.3

#84 parseEmail to ParseDate.
  src/main/java/seedu/equipment/logic/parser/AddCommandParser.java
  src/main/java/seedu/equipment/logic/parser/AddWorkListCommandParser.java
  src/main/java/seedu/equipment/logic/parser/EditCommandParser.java
  src/main/java/seedu/equipment/logic/parser/ParserUtil.java
  src/main/java/seedu/equipment/model/equipment/Date.java
  src/test/java/seedu/equipment/logic/parser/ParserUtilTest.java
Labels: priority.Low, type.Enhancement

#87 Modify the way coordinates are retrieved
  src/main/java/seedu/equipment/model/equipment/Address.java
  src/main/java/seedu/equipment/model/equipment/Equipment.java
Labels: priority.High, type.Task, v1.3
