Repository CS2103-AY1819S2-W10-3/main, pull requests merged in 2019-04, with the labels that each got.

#88 Update documentation and style in gh-pages
  docs/stylesheets/asciidoctor.css
  docs/stylesheets/gh-pages.css
Labels: documentation, v1.3

#90 Update ug and dg appearance and information
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ui_labelled.pptx
  docs/images/advanced.png
  docs/images/exclamation.png
  docs/images/lightbulb.png
  docs/images/tip.png
  docs/images/ui_labelled.png
  src/main/java/seedu/equipment/logic/commands/AddCommand.java
Labels: documentation, priority.High, type.Task, v1.3

#89 Display worklist
  src/main/java/seedu/equipment/logic/Logic.java
  src/main/java/seedu/equipment/logic/LogicManager.java
  src/main/java/seedu/equipment/model/EquipmentManager.java
  src/main/java/seedu/equipment/model/Model.java
  src/main/java/seedu/equipment/model/ModelManager.java
  src/main/java/seedu/equipment/model/ReadOnlyEquipmentManager.java
  src/main/java/seedu/equipment/model/UniqueWorkListList.java
  src/main/java/seedu/equipment/model/WorkList.java
  src/main/java/seedu/equipment/model/WorkListId.java
  src/main/java/seedu/equipment/model/equipment/exceptions/DuplicateEquipmentException.java
  src/main/java/seedu/equipment/ui/EquipmentListPanel.java
  src/main/java/seedu/equipment/ui/MainWindow.java
  src/main/java/seedu/equipment/ui/WorkListCard.java
  src/main/java/seedu/equipment/ui/WorkListListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/WorkListListCard.fxml
  src/main/resources/view/WorkListListPanel.fxml
  src/test/java/guitests/guihandles/WorkListCardHandle.java
  src/test/java/guitests/guihandles/WorkListListPanelHandle.java
  src/test/java/seedu/equipment/logic/commands/AddCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddWorkListCommandTest.java
  src/test/java/seedu/equipment/model/EquipmentManagerTest.java
  src/test/java/seedu/equipment/model/ModelManagerTest.java
  src/test/java/seedu/equipment/model/WorkListIdTest.java
  src/test/java/seedu/equipment/model/WorkListTest.java
  src/test/java/seedu/equipment/testutil/TypicalIndexes.java
  src/test/java/seedu/equipment/testutil/TypicalWorkLists.java
  src/test/java/seedu/equipment/ui/WorkListCardTest.java
  src/test/java/seedu/equipment/ui/WorkListListPanelTest.java
  src/test/java/seedu/equipment/ui/testutil/GuiTestAssert.java
Labels: priority.Medium, type.Story, v1.3

#91 Check if DateFormat is Valid and minor fixes
  src/main/java/seedu/equipment/commons/util/StringUtil.java
  src/main/java/seedu/equipment/logic/parser/CliSyntax.java
  src/main/java/seedu/equipment/model/equipment/Date.java
  src/main/java/seedu/equipment/model/equipment/DateContainsKeywordsPredicate.java
  src/main/java/seedu/equipment/model/equipment/EquipmentContainsKeywordsPredicate.java
  src/test/java/seedu/equipment/logic/commands/SortCommandTest.java
  src/test/java/seedu/equipment/model/equipment/DateTest.java
  src/test/java/seedu/equipment/ui/EquipmentListPanelTest.java
Labels: priority.High, type.Enhancement, v1.3

#94 Edit FilterCommand to filter specific field or multifield
  src/main/java/seedu/equipment/commons/util/StringUtil.java
  src/main/java/seedu/equipment/logic/parser/FilterCommandParser.java
  src/main/java/seedu/equipment/model/equipment/EquipmentContainsKeywordsPredicate.java
  src/test/java/seedu/equipment/logic/commands/FilterCommandTest.java
  src/test/java/seedu/equipment/logic/parser/FilterCommandParser.java
  src/test/java/seedu/equipment/logic/parser/FilterCommandParserTest.java
Labels: priority.High, type.Enhancement, type.Story, v1.3

#96 Add rachel.adoc ppp
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/rachel.adoc
Labels: documentation, type.Task, v1.3

#97 add-w command need one more attribute
  src/main/java/seedu/equipment/logic/commands/AddWorkListCommand.java
  src/main/java/seedu/equipment/logic/parser/AddWorkListCommandParser.java
  src/main/java/seedu/equipment/logic/parser/CliSyntax.java
  src/main/java/seedu/equipment/logic/parser/ParserUtil.java
  src/main/java/seedu/equipment/model/UniqueWorkListList.java
  src/main/java/seedu/equipment/model/WorkList.java
  src/main/java/seedu/equipment/model/WorkListId.java
  src/main/java/seedu/equipment/ui/WorkListCard.java
  src/test/java/guitests/guihandles/WorkListCardHandle.java
  src/test/java/seedu/equipment/logic/commands/CommandTestUtil.java
  src/test/java/seedu/equipment/logic/parser/AddWorkListCommandParserTest.java
  src/test/java/seedu/equipment/model/WorkListIdTest.java
  src/test/java/seedu/equipment/model/WorkListTest.java
  src/test/java/seedu/equipment/testutil/TypicalWorkLists.java
  src/test/java/seedu/equipment/testutil/WorkListBuilder.java
  src/test/java/seedu/equipment/ui/WorkListListPanelTest.java
Labels: priority.Medium, type.Enhancement, v1.3

#99 Update on UserGuide and PPP.
  docs/UserGuide.adoc
  docs/team/LiuXuan.adoc
Labels: documentation, priority.Low, v1.3

#98 Add equipment detail page
  docs/UserGuide.adoc
  docs/staticpages/DisplayEquipmentDetail.html
  src/main/java/seedu/equipment/ui/BrowserPanel.java
  src/main/java/seedu/equipment/ui/MainWindow.java
  src/test/java/seedu/equipment/ui/BrowserPanelTest.java
  src/test/java/systemtests/EquipmentManagerSystemTest.java
Labels: priority.Medium, type.Enhancement, v1.3

#100 Update ppp
  docs/AboutUs.adoc
  docs/team/yiqun.adoc
Labels: priority.High, type.Task, v1.3

#102 Fix reference issues in PPP
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/team/yiqun.adoc
Labels: priority.High, type.bug, v1.3

#101 Update PPP
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/stylesheets/meiyen.css
  docs/team/meiyen.adoc
Labels: documentation, priority.High, type.Task, v1.3

#107 Fix tags in UG
  docs/UserGuide.adoc
Labels: priority.High, severity.High, type.bug, v1.3

#108 Add developer guide back
  docs/DeveloperGuide.adoc
Labels: documentation, severity.High, type.bug

#103 List Client details (list-c command)
  docs/UserGuide.adoc
  docs/team/johndoe.adoc
  docs/team/rachel.adoc
  src/main/java/seedu/equipment/logic/Logic.java
  src/main/java/seedu/equipment/logic/LogicManager.java
  src/main/java/seedu/equipment/logic/commands/EditCommand.java
  src/main/java/seedu/equipment/logic/commands/ListClientCommand.java
  src/main/java/seedu/equipment/logic/commands/ListEquipmentCommand.java
  src/main/java/seedu/equipment/logic/commands/RedoCommand.java
  src/main/java/seedu/equipment/logic/commands/UndoCommand.java
  src/main/java/seedu/equipment/logic/parser/EquipmentManagerParser.java
  src/main/java/seedu/equipment/model/Model.java
  src/main/java/seedu/equipment/model/ModelManager.java
  src/main/java/seedu/equipment/ui/ClientListCard.java
  src/main/java/seedu/equipment/ui/ClientListPanel.java
  src/main/java/seedu/equipment/ui/EquipmentListPanel.java
  src/main/java/seedu/equipment/ui/MainWindow.java
  src/main/java/seedu/equipment/ui/ResultDisplay.java
  src/main/java/seedu/equipment/ui/UiManager.java
  src/main/resources/view/ClientListCard.fxml
  src/test/java/seedu/equipment/logic/LogicManagerTest.java
  src/test/java/seedu/equipment/logic/commands/AddCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddWorkListCommandTest.java
  src/test/java/seedu/equipment/logic/commands/ListClientCommandTest.java
  src/test/java/seedu/equipment/logic/parser/EquipmentManagerParserTest.java
  src/test/java/seedu/equipment/model/ModelManagerTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: documentation, priority.High, type.Enhancement, type.Story, type.Task, v1.4

#109 Put command
  src/main/java/seedu/equipment/logic/commands/PutCommand.java
  src/main/java/seedu/equipment/logic/parser/EquipmentManagerParser.java
  src/main/java/seedu/equipment/logic/parser/PutCommandParser.java
  src/main/java/seedu/equipment/model/EquipmentManager.java
  src/main/java/seedu/equipment/model/Model.java
  src/main/java/seedu/equipment/model/ModelManager.java
  src/main/java/seedu/equipment/model/UniqueWorkListList.java
  src/main/java/seedu/equipment/model/WorkList.java
  src/main/java/seedu/equipment/model/equipment/UniqueEquipmentList.java
  src/test/java/seedu/equipment/logic/commands/AddCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddWorkListCommandTest.java
  src/test/java/seedu/equipment/logic/commands/CommandTestUtil.java
  src/test/java/seedu/equipment/logic/commands/PutCommandTest.java
  src/test/java/seedu/equipment/logic/parser/PutCommandParserTest.java
  src/test/java/seedu/equipment/model/UniqueWorkListListTest.java
  src/test/java/seedu/equipment/model/equipment/UniqueEquipmentListTest.java
Labels: priority.High, type.Story, v1.3

#111 Add UI, Equipment, Client feature in DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/applaunchUI.png
  docs/images/clientlocationsUI.png
  docs/images/equipmentdetailsUI.png
  docs/team/rachel.adoc
Labels: documentation, type.Task, v1.4

#112 Refactor Email to Date
  src/test/java/guitests/guihandles/EquipmentCardHandle.java
  src/test/java/seedu/equipment/model/equipment/DateTest.java
  src/test/java/seedu/equipment/storage/JsonAdaptedEquipmentTest.java
  src/test/java/seedu/equipment/ui/testutil/GuiTestAssert.java
Labels: priority.High, type.Task, v1.3

#114 Modify some UI part regarding the WorkList
  docs/team/LiuXuan.adoc
  src/main/java/seedu/equipment/logic/commands/PutCommand.java
  src/main/java/seedu/equipment/model/EquipmentManager.java
  src/main/java/seedu/equipment/model/Model.java
  src/main/java/seedu/equipment/model/ModelManager.java
  src/main/java/seedu/equipment/model/WorkListId.java
  src/main/java/seedu/equipment/model/equipment/UniqueEquipmentList.java
  src/main/java/seedu/equipment/ui/WorkListCard.java
  src/main/resources/view/WorkListListCard.fxml
  src/test/java/seedu/equipment/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddWorkListCommandTest.java
  src/test/java/seedu/equipment/logic/commands/PutCommandTest.java
  src/test/java/seedu/equipment/model/EquipmentManagerTest.java
  src/test/java/seedu/equipment/model/equipment/UniqueEquipmentListTest.java
  src/test/java/seedu/equipment/ui/testutil/GuiTestAssert.java
Labels: priority.Medium, type.Enhancement, v1.4

#175 Update UG and PPP for client panel feature
  docs/UserGuide.adoc
  docs/team/rachel.adoc
Labels: documentation, type.Task, v1.4

#176 Update DG and UG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/meiyen.adoc
Labels: documentation, type.Story, v1.4

#177 Create static pages for routing
  docs/staticpages/DisplayRoutes.html
Labels: priority.High, type.Task, v1.4

#178 edit SortCommand to sort by date and change date format
  docs/UserGuide.adoc
  src/main/java/seedu/equipment/logic/commands/AddCommand.java
  src/main/java/seedu/equipment/logic/commands/AddWorkListCommand.java
  src/main/java/seedu/equipment/logic/commands/FilterCommand.java
  src/main/java/seedu/equipment/logic/commands/SortCommand.java
  src/main/java/seedu/equipment/logic/parser/AddWorkListCommandParser.java
  src/main/java/seedu/equipment/logic/parser/CliSyntax.java
  src/main/java/seedu/equipment/logic/parser/DateComparator.java
  src/main/java/seedu/equipment/logic/parser/EquipmentManagerParser.java
  src/main/java/seedu/equipment/logic/parser/NameComparator.java
  src/main/java/seedu/equipment/logic/parser/PhoneComparator.java
  src/main/java/seedu/equipment/logic/parser/SerialNumberComparator.java
  src/main/java/seedu/equipment/logic/parser/SortCommandParser.java
  src/main/java/seedu/equipment/model/EquipmentManager.java
  src/main/java/seedu/equipment/model/Model.java
  src/main/java/seedu/equipment/model/ModelManager.java
  src/main/java/seedu/equipment/model/UniqueWorkListList.java
  src/main/java/seedu/equipment/model/equipment/Date.java
  src/main/java/seedu/equipment/model/equipment/EquipmentContainsKeywordsPredicate.java
  src/main/java/seedu/equipment/model/equipment/UniqueEquipmentList.java
  src/main/java/seedu/equipment/model/util/SampleDataUtil.java
  src/main/java/seedu/equipment/storage/JsonAdaptedEquipment.java
  src/main/java/seedu/equipment/ui/EquipmentCard.java
  src/test/data/JsonEquipmentManagerStorageTest/invalidAndValidEquipmentEM.json
  src/test/data/JsonEquipmentManagerStorageTest/invalidEquipmentEM.json
  src/test/data/JsonSerializableEquipmentManagerTest/duplicateEquipmentEM.json
  src/test/data/JsonSerializableEquipmentManagerTest/typicalEquipmentEM.json
  src/test/java/guitests/guihandles/EquipmentCardHandle.java
  src/test/java/seedu/equipment/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddWorkListCommandTest.java
  src/test/java/seedu/equipment/logic/commands/CommandTestUtil.java
  src/test/java/seedu/equipment/logic/commands/FilterCommandTest.java
  src/test/java/seedu/equipment/logic/commands/SortCommandTest.java
  src/test/java/seedu/equipment/logic/parser/EquipmentManagerParserTest.java
  src/test/java/seedu/equipment/logic/parser/ParserUtilTest.java
  src/test/java/seedu/equipment/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/equipment/model/equipment/DateTest.java
  src/test/java/seedu/equipment/model/equipment/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/equipment/storage/JsonAdaptedEquipmentTest.java
  src/test/java/seedu/equipment/testutil/EquipmentBuilder.java
  src/test/java/seedu/equipment/testutil/EquipmentUtil.java
  src/test/java/seedu/equipment/testutil/TypicalEquipments.java
  src/test/java/seedu/equipment/testutil/TypicalWorkLists.java
  src/test/java/seedu/equipment/ui/EquipmentListPanelTest.java
  src/test/java/seedu/equipment/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: documentation, priority.High, type.Enhancement, type.Task, v1.4

#180 Update dg and ug
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddCommandSD.pptx
  docs/diagrams/DeletePersonSdForLogic.pptx
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/diagrams/ui_labelled.pptx
  docs/images/AddClientDetailsUI.png
  docs/images/AddCommandSD.png
  docs/images/DeletePersonSdForLogic.png
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SDforDeletePerson.png
  docs/images/UI.png
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/images/ui_labelled.png
  gradle/wrapper/gradle-wrapper.properties
Labels: documentation, type.Enhancement, type.Task, v1.4

#179 Implement route feature
  docs/staticpages/DisplayRoutes.html
  src/main/java/seedu/equipment/logic/commands/CommandResult.java
  src/main/java/seedu/equipment/logic/commands/RouteCommand.java
  src/main/java/seedu/equipment/logic/parser/EquipmentManagerParser.java
  src/main/java/seedu/equipment/logic/parser/RouteCommandParser.java
  src/main/java/seedu/equipment/ui/BrowserPanel.java
  src/main/java/seedu/equipment/ui/MainWindow.java
  src/test/java/seedu/equipment/logic/commands/RouteCommandTest.java
  src/test/java/systemtests/EquipmentManagerSystemTest.java
  src/test/java/systemtests/RouteCommandSystemTest.java
Labels: priority.High, type.Story, v1.4

#182 Delete command
  docs/UserGuide.adoc
  src/main/java/seedu/equipment/logic/commands/DeleteWorkListCommand.java
  src/main/java/seedu/equipment/logic/commands/PutCommand.java
  src/main/java/seedu/equipment/logic/commands/RemoveCommand.java
  src/main/java/seedu/equipment/logic/parser/DeleteWorkListCommandParser.java
  src/main/java/seedu/equipment/logic/parser/EquipmentManagerParser.java
  src/main/java/seedu/equipment/model/EquipmentManager.java
  src/main/java/seedu/equipment/model/Model.java
  src/main/java/seedu/equipment/model/ModelManager.java
  src/main/java/seedu/equipment/model/UniqueWorkListList.java
  src/main/java/seedu/equipment/model/WorkList.java
  src/test/java/seedu/equipment/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddWorkListCommandTest.java
  src/test/java/seedu/equipment/logic/commands/DeleteWorkListCommandTest.java
  src/test/java/seedu/equipment/logic/parser/DeleteWorkListCommandParserTest.java
  src/test/java/seedu/equipment/testutil/TestUtil.java
  src/test/java/systemtests/DeleteWorkListCommandSystemTest.java
  src/test/java/systemtests/PutCommandSystemTest.java
  src/test/java/systemtests/RemoveCommandSystemTest.java
Labels: documentation, priority.High, type.Story, v1.4

#186 Fix select display select bug
  src/main/java/seedu/equipment/logic/commands/DisplayCommand.java
  src/main/java/seedu/equipment/logic/commands/RouteCommand.java
  src/main/java/seedu/equipment/model/Model.java
  src/main/java/seedu/equipment/model/ModelManager.java
  src/main/java/seedu/equipment/ui/BrowserPanel.java
  src/test/java/seedu/equipment/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddWorkListCommandTest.java
  src/test/java/systemtests/DisplayCommandSystemTest.java
  src/test/java/systemtests/RouteCommandSystemTest.java
Labels: priority.High, severity.High, type.bug, v1.4

#187 Fix reposense
  _reposense/config.json
Labels: type.Task, v1.4

#185 Fix Client Panel and Enhance Equipment Details
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/rachel.adoc
  src/main/java/seedu/equipment/commons/core/Messages.java
  src/main/java/seedu/equipment/logic/Logic.java
  src/main/java/seedu/equipment/logic/LogicManager.java
  src/main/java/seedu/equipment/logic/commands/AddClientCommand.java
  src/main/java/seedu/equipment/logic/commands/CommandResult.java
  src/main/java/seedu/equipment/logic/commands/ListClientCommand.java
  src/main/java/seedu/equipment/logic/commands/SelectClientCommand.java
  src/main/java/seedu/equipment/logic/parser/AddClientCommandParser.java
  src/main/java/seedu/equipment/logic/parser/EquipmentManagerParser.java
  src/main/java/seedu/equipment/logic/parser/SelectClientCommandParser.java
  src/main/java/seedu/equipment/model/Model.java
  src/main/java/seedu/equipment/model/ModelManager.java
  src/main/java/seedu/equipment/storage/JsonEquipmentManagerStorage.java
  src/main/java/seedu/equipment/storage/JsonSerializableEquipmentManager.java
  src/main/java/seedu/equipment/ui/ClientListPanel.java
  src/main/java/seedu/equipment/ui/EquipmentListPanel.java
  src/main/java/seedu/equipment/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/GuiRobot.java
  src/test/java/seedu/equipment/logic/commands/AddClientCommandIntegrationTest.java
  src/test/java/seedu/equipment/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddCommandTest.java
  src/test/java/seedu/equipment/logic/commands/AddWorkListCommandTest.java
  src/test/java/seedu/equipment/logic/commands/ListClientCommandTest.java
  src/test/java/seedu/equipment/logic/commands/SelectClientCommandTest.java
  src/test/java/seedu/equipment/logic/parser/AddClientCommandParserTest.java
  src/test/java/seedu/equipment/logic/parser/EquipmentManagerParserTest.java
  src/test/java/seedu/equipment/logic/parser/SelectClientCommandParserTest.java
  src/test/java/seedu/equipment/testutil/TypicalIndexes.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
Labels: documentation, priority.High, type.Enhancement, type.Story, type.Task, type.bug, v1.4

#188 Update UG and DG diagrams
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/SortCommandSequenceDiagram.pptx
  docs/diagrams/UndoRedoActivityDiagram.pptx
  docs/diagrams/UndoRedoExecuteUndoStateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand1StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand2StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand3StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand4StateListDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagramtest.png
  docs/diagrams/UndoRedoStartingStateListDiagram.pptx
  docs/images/SortCommandSequenceDiagram.png
  docs/images/UndoRedoActivityDiagram.png
  docs/images/UndoRedoExecuteUndoStateListDiagram.png
  docs/images/UndoRedoNewCommand1StateListDiagram.png
  docs/images/UndoRedoNewCommand2StateListDiagram.png
  docs/images/UndoRedoNewCommand3StateListDiagram.png
  docs/images/UndoRedoNewCommand4StateListDiagram.png
  docs/images/UndoRedoSequenceDiagram.png
  docs/images/UndoRedoStartingStateListDiagram.png
  docs/images/filteraddress.png
  docs/images/filterdate.png
  docs/images/filtermultiple.png
  docs/images/filtername.png
  docs/images/filterphone.png
  docs/images/filterserial.png
  docs/images/filtertags.png
  docs/images/sortDate.png
  docs/images/sortName.png
  docs/images/sortPhone.png
  docs/images/sortSerial.png
  docs/team/meiyen.adoc
Labels: documentation, priority.High, v1.4

#189 Update DG, UG, PPP
  docs/UserGuide.adoc
  docs/images/PendingCC.png
  docs/images/SerangoonCC.png
  docs/images/UiClassDiagram.png
  docs/team/rachel.adoc
  src/main/java/seedu/equipment/logic/commands/AddCommand.java
Labels: documentation, type.Task, v1.4

#190 Fix typos in UG and DG and PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/meiyen.adoc
Labels: documentation, priority.Medium, v1.4

#192 Fix Client panels
  src/main/java/seedu/equipment/logic/commands/AddCommand.java
  src/main/java/seedu/equipment/model/EquipmentManager.java
  src/main/java/seedu/equipment/model/ModelManager.java
  src/main/java/seedu/equipment/model/equipment/UniqueNameList.java
  src/main/java/seedu/equipment/ui/ClientListPanel.java
Labels: priority.High, type.Task, type.bug, v1.4

#194 Fix clear command to work on client panel
  src/main/java/seedu/equipment/model/EquipmentManager.java
  src/main/java/seedu/equipment/model/equipment/UniqueNameList.java
Labels: type.bug, v1.4

#195 Final Documentation update - Rachel
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddCommandSD.pptx
  docs/diagrams/SelectClientCommandSD.pptx
  docs/diagrams/~$FilterCommandSequenceDiagram.pptx
  docs/images/AddClientDetailsUI.png
  docs/images/AddCommandSD.png
  docs/images/SelectClientUC.png
  docs/images/clientlocationsUI.png
  docs/images/equipmentdetailsUI.png
  docs/team/rachel.adoc
  src/main/java/seedu/equipment/model/util/.SampleDataUtil.java.swp
Labels: documentation

#197 Update manual testing for sort and filter command in DG
  docs/DeveloperGuide.adoc
Labels: documentation, v1.4

#196 Update docs yiqun
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/DisplayActivityDiagrams.pptx
  docs/diagrams/DisplaySequenceDiagram.pptx
  docs/diagrams/RouteSequenceDiagram.pptx
  docs/images/DisplayActivityDiagram.png
  docs/images/DisplaySequenceDiagram.png
  docs/images/RouteSequenceDiagram.png
  docs/team/dukesun99.adoc
  docs/team/yiqun.adoc
Labels: documentation, v1.4

#198 Yiqun update images
  docs/UserGuide.adoc
  docs/images/display-screenshot.png
  docs/images/route-planning-screenshot.png
Labels: documentation
